name: Terraform plan

on:
  workflow_dispatch:

  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

# Need ID token write permission to use OIDC
permissions:
  id-token: write
  contents: read


jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: examples/s3-only

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.16.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{vars.AWS_REGION}}
      - name: Additional steps
        run: |
          terraform plan \
            -input=false \
