name: Terraform plan

on:
  workflow_dispatch:

  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

# Need ID token write permission to use OIDC
permissions:
  id-token: write
  contents: read


jobs:
  run_job_with_aws:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: examples/s3-only

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.16.0"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{vars.AWS_REGION}}
          role-skip-session-tagging: true

      - name: Assume second role
        uses: aws-actions/configure-aws-credentials@v6.3.0
        with:
          aws-region: ${{vars.AWS_REGION}}
          role-to-assume: ${{secrets.AWS_DEV_ROLE_ARN}}
          role-chaining: true
          role-skip-session-tagging: true

      - name: Terraform fmt
        run: terraform fmt -check -recursive

      - name: Terraform init
        run: |
          terraform init \
            -input=false 

      - name: Terraform plan
        run: |
          terraform plan \
            -input=false \
